# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d54f09ea14a592cc36b4d1ade67c3ab2d0e55fcf60a60f690500bf7e735d17de739e8b9d0db26ff08e60c7f25654ff2e07d20587b0fdb9d8f6c1dffa38d6f17

test:
  secret_key_base: dd723ee10d58ec377f596bf87639cd22cd5bb600aba9f0244e80d62e8221c681ddb9ee3b61115c058f694de4fc9ea2cfb192f15c14b4d9ca2e4ec98c2de370fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
